In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [8]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9444444444444444

In [9]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [10]:
rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9555555555555556

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [29]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

In [31]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=30), X_train, X_test, y_train, y_test))



In [32]:
scores_lr

[0.9055555555555556,
 0.9555555555555556,
 0.8833333333333333,
 0.9333333333333333,
 0.9388888888888889,
 0.95,
 0.95,
 0.9329608938547486,
 0.88268156424581,
 0.9441340782122905]

In [33]:
scores_svm

[0.9444444444444444,
 0.9888888888888889,
 0.9277777777777778,
 0.9666666666666667,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9608938547486033,
 0.9553072625698324]

In [34]:
scores_rf

[0.9055555555555556,
 0.9722222222222222,
 0.9722222222222222,
 0.8944444444444445,
 0.9666666666666667,
 0.9722222222222222,
 0.9611111111111111,
 0.9664804469273743,
 0.9329608938547486,
 0.9441340782122905]

In [35]:
from sklearn.model_selection import cross_val_score

In [41]:
lr_score = (cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target,cv=10)).mean()

In [42]:
svc_score = (cross_val_score(SVC(), digits.data, digits.target,cv=10)).mean()

In [43]:
rf_score = (cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=10)).mean()

In [44]:
print(lr_score, svc_score, rf_score)

0.9276443202979516 0.9699503414028554 0.9477001862197392
